config/routes.rb
Rails.application.routes.draw do
  get 'interviews/index'
 
  root to: "interviews#index"

  get "interviews/question" => "interviews#question"
  get "interviews/start" => "interviews#start"
  get "interviews/finish" => "interviews#finish"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/interview.rb
class Interview < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController

  INTERVIEWS_ORDER_KEY = "interviews_order"
  CURRENT_INTERVIEW_INDEX_KEY = "current_interview_index"

  def index
  end

  def start
    reset_session # セッションをリセット
  end

  def question
    show_page
  end

  def finish
  end

  private

  def show_page
      # 以前に表示したページがあれば取得、なければ初期化
      @interviews_order = session[INTERVIEWS_ORDER_KEY] || Interview.pluck(:id).shuffle
      @current_interview_index = session[CURRENT_INTERVIEW_INDEX_KEY].to_i || 0

    if @current_interview_index < 10
      @current_interview_id = @interviews_order[@current_interview_index]
      @current_interview = Interview.find(@current_interview_id)

      # 一度表示したデータは削除
      @interviews_order.delete(@current_interview_id)
      session[INTERVIEWS_ORDER_KEY] = @interviews_order

      session[CURRENT_INTERVIEW_INDEX_KEY] = (@current_interview_index + 1)
    else
      redirect_to interviews_finish_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/views/interviews/_header.html.erb
<div class="head_bar">
  <div class="title">
    <div class="title-logo">エントレ面接</div>
  </div>
  <div class="retry">
    <%# <div class="retry-btn">リトライ</div> %>
    <%= link_to "リトライ", root_path, class: "retry-btn" %>
  </div>

</div>

app/views/interviews/_opening.html.erb
      <div class="mensetu">面接開始</div>
      <div class="setumei"><span class="ten">１０</span>の質問に答える</div>
      <div class="setumei-block">
        <div class="category">
          <div class="category-head"> 何度も練習</div>
          <div class="category-bottom">
            <%= image_tag 'voice.png', class: 'icon' %>
            <br>面接は暗記勝負ではありません。話し方は変わっても伝えたい思いは変わらぬよう何度も練習しましょう。</div>
        </div>
         <div class="category">
          <div class="category-head"> PCで練習</div>
          <div class="category-bottom">
            <%= image_tag 'laptop.png', class: 'icon' %>
            <br>WEB面接は画面の大きいPCがやり易いです。面接本番に近い環境で練習をしましょう。</div>
        </div>
        <div class="category">
          <div class="category-head"> エンジニア向け</div>
          <div class="category-bottom">
            <%= image_tag 'program.png', class: 'icon' %>
            <br>これからエンジニアを目指す方が質問され易い内容です。一般的な質問だけでなく技術的な質問にも答えられるよう練習しましょう。</div>
        </div>  
      </div>
      <div class="start">
        <%= link_to "さぁ始めよう", interviews_start_path, class: "start-btn" %>
      </div>

app/views/interviews/_start.html.erb
      <div class="mensetu">面接開始</div>
      <div class="setumei"><span class="ten">１０</span>の質問に答える</div>
      <div class="setumei-block">
        <div class="category">
          <div class="category-head"> 何度も練習</div>
          <div class="category-bottom">
            <%= image_tag 'voice.png', class: 'icon' %>
            <br>面接は暗記勝負ではありません。話し方は変わっても伝えたい思いは変わらぬよう何度も練習しましょう。</div>
        </div>
         <div class="category">
          <div class="category-head"> PCで練習</div>
          <div class="category-bottom">
            <%= image_tag 'laptop.png', class: 'icon' %>
            <br>WEB面接は画面の大きいPCがやり易いです。面接本番に近い環境で練習をしましょう。</div>
        </div>
        <div class="category">
          <div class="category-head"> エンジニア向け</div>
          <div class="category-bottom">
            <%= image_tag 'program.png', class: 'icon' %>
            <br>これからエンジニアを目指す方が質問され易い内容です。一般的な質問だけでなく技術的な質問にも答えられるよう練習しましょう。</div>
        </div>  
      </div>
      <div class="start">
        <div class="start-btn">さぁ始めよう</div>
      </div>

app/views/interviews/finish.html.erb
<div class="wrapper">
  <div class="header">
    <%= render "header" %>
  </div>
  <div class="main">
    <div class="content">
      
      <div class="question">お疲れ様でした</div>
      <div class="next">
        <%= link_to "トップへ", root_path, class: "bottom-link" %>
      </div>
    </div> 
  </div>

  

</div>

app/views/interviews/index.html.erb
<div class="wrapper">
  <div class="header">
    <%= render "header" %>
  </div>
  <div class="main">
    <div class="content">

      <%= render "opening" %>

    </div>    
  </div>

  

</div>

app/views/interviews/question.html.erb
<div class="wrapper">
  <div class="header">
    <%= render "header" %>
  </div>
  <div class="main">
    <div class="content">

      <%= tag.div @current_interview.question, class: "question" %>
      <div class="next">
        <%= link_to "次へ", interviews_question_path, class: "bottom-link" %>
      </div>

    </div>    
  </div>

</div>

app/views/interviews/start.html.erb
<div class="wrapper">
  <div class="header">
    <%= render "header" %>
  </div>
  <div class="main">
    <div class="content">

        <div class="question">自己紹介をお願いします</div>
        <%= link_to "次へ", interviews_question_path, class: "next" %>

    </div> 
  </div>

  

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mensetusiyoyo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/earlyaccess/nicomoji.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Sawarabi+Gothic" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Zen+Kaku+Gothic+New&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "interviews", "data-turbo-track": "reload" %>

<link href="https://fonts.googleapis.com/css2?family=Dela+Gothic+One&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Kaisei+Opti&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Sawarabi+Gothic&display=swap" rel="stylesheet">

<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">


    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>